[package]
name = "rust_assign"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.15.2"
bs58 = "0.5.1"
solana-program = "1.15.2"
borsh = "0.10.3"
solana-client = "2.0"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }